title: Rebekah's Example Page
logo: /assets/img/logo.png
description: Geospatial Data Science in Python.
show_downloads: false
repository: MUSA-550-Fall-2021/github-pages-single-page-starter
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
sitename: Rebekah's Exercise
